
package com.javaapi.test.application.rpc.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldImpl", targetNamespace = "http://server.webservice.rpc.application.test.javaapi.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.javaapi.test.application.rpc.webservice.client.HelloResp
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://server.webservice.rpc.application.test.javaapi.com/", className = "com.javaapi.test.application.rpc.webservice.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://server.webservice.rpc.application.test.javaapi.com/", className = "com.javaapi.test.application.rpc.webservice.client.SayHelloResponse")
    @Action(input = "http://server.webservice.rpc.application.test.javaapi.com/HelloWorldImpl/sayHelloRequest", output = "http://server.webservice.rpc.application.test.javaapi.com/HelloWorldImpl/sayHelloResponse")
    public HelloResp sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        HelloReq arg0);

}
