package com.javaapi.test.test.misc.codegenerator.practice.dataobject;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table workflow_form
 *
 * @mbg.generated do_not_delete_during_merge Tue Mar 19 14:02:55 CST 2019
 */
public class OrderDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column workflow_form.id
     *
     * @mbg.generated Tue Mar 19 14:02:55 CST 2019
     */
    private Long id;

    private String title;

}